# Generated by Django 5.0.3 on 2024-03-17 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
